### ISSUE TITLE
Portable releases

### ISSUE THREAD

**Issue by KOLANICH** [dmikushin/usbsnoop#7]
No installer, just an archive.

**Comment by dmikushin** [comment]
USBSnoop release is just a tiny .exe file for the corresponding architecture. It embeds drivers as resources. So there is little need for installer, except that one might want to use it to automate installation of  visual studio redist runtime.

**Comment by KOLANICH** [comment]
Thank you for the clarification.

>It embeds drivers as resources.

Could this be done another way, keeping all the files as separate files?

**Comment by dmikushin** [comment]
For sure, one can develop an installation package. However, for such a tool we should expect an "advanced" user, who can live without a fancy installer. So personally I would not invest time into this. But contributions are very welcome! Consider, for example [WiX](http://wixtoolset.org/).

**Comment by KOLANICH** [comment]
>For sure, one can develop an installation package. However, for such a tool we should expect an "advanced" user, who can live without a fancy installer. So personally I would not invest time into this. But contributions are very welcome! Consider, for example WiX.

I mean no installation package at all, just a portable version. I mean the following look&feel: a user just unpacks an archive (Windows has the archiver out of the box) into a folder and the app is ready to use. Registering and unregistering the driver into/from registry and cleaning up after the previous runs is done by the app itself. But the files lie in the folder, not in the resources.

**Comment by dmikushin** [comment]
OK, current .exe unpacks .sys files directly into `system32/drivers` anyway. Keeping them in initial folder is just a duplicate IMO. Personally I don't want this because of the need to bother with file system locations, e.g. "find which path .exe is at, locate other files in the same path, show error if not found, etc. etc.".

**Comment by KOLANICH** [comment]
>current .exe unpacks .sys files directly into system32/drivers anyway

Can this be avoided? I mean if a driver can be installed without copying anything into `system32` only by registry modification?

>Personally I don't want this because of the need to bother with file system locations, e.g. "find which path .exe is at, locate other files in the same path, show error if not found, etc. etc.".

BTW, fs api is present in current C++ draft.
